<?php
$email = $_GET['email'];
$correo = "<table width='660' border='0' align='center' cellpadding='1' cellspacing='0' bgcolor='#CCCCCC'><tr><td><table width='100%'' border='0' cellspacing='0' cellpadding='0'><tr><td height='130' align='center' bgcolor='#f5f6f7'><img src='http://www.latamxpress.com/app/img/logo_mail.png' width='231' height='72' /></td></tr></table></td></tr><tr><td><table border='0' align='center' cellpadding='30' cellspacing='0'><tr><td valign='top' bgcolor='#FFFFFF'><h1 style='font-family: Verdana, Geneva, sans-serif;font-size: 22px; color: #333333; font-weight: bold; letter-spacing: -1px;'>Bienvenido</h1><p><span style='font-family: Verdana, Geneva, sans-serif; font-size: 13px; color: #000000;'>Gracias por escogernos como tu courier de confianza. Para continuar con el proceso de registro haz clic aqu&iacute;:</span><br /><br /></p><table width='250' border='1' align='center' cellpadding='15' cellspacing='0'><tr>";
$correo .= "<td align='center' bgcolor='#21619D'><strong><a class='btn btn-info' role='button' href='http://www.latamxpress.com/app/exitoRegistro.php?Email=".$email."' style='font-family: Verdana, Geneva, sans-serif; font-size: 13px; color: #FFF;'>CONFIRMAR REGISTRO</a></strong></td>";
$correo .= "</tr></table><p>&nbsp;</p><p style='font-family: Verdana, Geneva, sans-serif; font-size: 13px; color: #777777;'><strong>¿No funciona el bot&oacute;n? </strong><br />Prueba copiando y pegando la siguiente direcci&oacute;n en tu navegador:<br />http://www.latamxpress.com/app/exitoRegistro.php?Email=".$email."</p><p><span>-------------------------------------------------------------------------------------</span><br /></td></tr><tr><td valign='top' bgcolor='#FFFFFF'><table width='100%' border='0' cellspacing='0' cellpadding='0'><tr><td><span><img src='http://www.latamxpress.com/app/img/firma.png' width='176' height='39' /></span></td><td align='right'><img src='http://www.latamxpress.com/app/img/tetraemos.jpg' width='201' height='16' /></td></tr></table></td></tr></table></td></tr><tr><td><table width='100%' border='0' cellspacing='0' cellpadding='30'><tr>
<td bgcolor='#FFFFFF'><p style='font-family: Verdana, Geneva, sans-serif; font-size: 10px; color: #333333;'><strong>Por favor no responder a este mensaje ya que el mismo fue enviado desde una cuenta de correo electr&oacute;nico no monitoreada. </strong></p><p style='font-family: Verdana, Geneva, sans-serif; font-size: 10px; color: #333333;' dir='ltr'>Tu contrase&ntilde;a es confidencial, LatamXpress® nunca solicitar&aacute; datos de tu cuenta y contrase&ntilde;a por correo electr&oacute;nico ni por ning&uacute;n otro medio.</p><p dir='ltr'><strong style='font-family: Verdana, Geneva, sans-serif; font-size: 10px; color: #333333;' id='docs-internal-guid-76b42a8c-6675-d983-e14a-bd00f1c486aa'>¿Dudas? escribenos a info@latamxpress.com y te ayudaremos</strong></p></td></tr></table></td></tr><tr><td align='center'><table width='100%' border='0' cellspacing='0' cellpadding='20' style='font-family: Verdana, Geneva, sans-serif; font-size: 13px; color: #FFFFFF; text-decoration: none;'><tr><td align='center' valign='top' bgcolor='#21619D' style='font-family: Verdana, Geneva, sans-serif; font-size: 13px; color: #FFFFFF; text-decoration: none;'><strong>Miami - Estados Unidos</strong><br />8000 NW 29th St,<br />Miami,FL 33122<br /><br />+1(305)640-5391<br />+1(305)640-5639</td><td align='center' valign='top' bgcolor='#21619D'><strong>Caracas - Venezuela</strong><br />+58(212)655-0603<br />RIF:J-000000-0 <br /><br /><br /><a href='http://www.latamxpress.com' style='font-family: Verdana, Geneva, sans-serif; font-size: 13px; color: #FFFFFF; text-decoration: none;'><strong>www.latamxpress.com</strong></a></td><td width='30%' align='center' valign='top' bgcolor='#21619D'><strong>Síguenos en:</strong><br /><br /><table width='100%' border='0' cellspacing='0' cellpadding='2'><tr><td><a href='https://www.facebook.com/Latam-Xpress-1049926855020369/?fref=ts' target='_blank'><img src='http://www.latamxpress.com/app/img/facebook.png' width='38' height='38' /></a></td><td><a href='https://www.instagram.com/latamxpress/' target='_blank'><img src='http://www.latamxpress.com/app/img/instagram.png' width='39' height='38' /></a></td><td><a href='https://twitter.com/latamxpress' target='_blank'><img src='http://www.latamxpress.com/app/img/twitter.png' width='38' height='38' /></a></td><td><a href='https://www.youtube.com/channel/UCfHfXf1oNSKP9wlPNn9_TwA' target='_blank'><img src='http://www.latamxpress.com/app/img/youtube.png' width='38' height='38' /></a></td></tr></table></td></tr></table></td></tr></table>";
$titulo3 = "Confirmación de Registro en LatamXpress";
//cabecera
$headers = "MIME-Version: 1.0\r\n";
$headers .= "Content-type: text/html; charset=utf-8\r\n";
//direcci&oacute;n del remitente
$headers .= "From: LatamXpress <no-responder@latamxpress.com.ve>\r\n";
$headers .= "Bcc: alexcampos@latamxpress.com\r\n";
//Enviamos el mensaje a tu_direcci&oacute;n_email
$bool = mail($email,$titulo3,$correo,$headers);
?>